version: "3"
services:
    posteeui:
        build:
            context: .
        ports:
            - 8000:8000
        environment:
            - "POSTEE_UI_CFG=~/cfg.yaml"
            - "POSTEE_UI_DB=/server/database/webhooks.db"
            - "POSTEE_UI_PORT=8000"